# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

# See also https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python
name: Publish to PyPI

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Clean repository before build
        run: git clean -fxd

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip wheel setuptools setuptools_scm build twine

      - name: Build package
        run: python -m build --sdist --wheel . --outdir dist

      - name: Check built distributions
        run: python -m twine check dist/*

      - name: Publish to PyPI
        if: success() && github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
